### ISSUE TITLE
Support for Anki alpha

### ISSUE THREAD

**Issue by FooSoft** [ninja33/anki-dict-helper#13]
Hey, you might want to check out my changes to the AnkiConnect project. I made it so that the same python script can be used in both stable (2.0.x) and alpha (2.1.x) releases of Anki. I also fixed a nasty hang bug that would happen if you would try to download audio when there was no network connection available.

**Comment by ninja33** [comment]
Thanks for your effort and heads up.

Actually, after they disabled that unofficial ankiweb interface, ankiconnect is de facto standard which was referred by dae himself in [support forum](https://anki.tenderapp.com/discussions/ankiweb/1886-issue-with-saving-cards-via-rest-api)
At least, they recognized it as acceptable way. 

I will try your new version. 
BTW, as you mentioned audio network connection, that reminds me one thing I always forgot asking. Could you make audio base-URL as a function parameter, currently I have to hard coding in ankiconnect.py and ask my community members download customized version to retrieve audio from an en-cn online dictionary. I think it's not best practice if they can not download ankiconnect by addon code, because they are going to miss some important upgrade in the future.

**Comment by FooSoft** [comment]
I think what I will do is provide an optional audio URL that you can specify in your request to add cards. This way you can just build your audio path in the extension and we can use the same plugin in Anki :cat:

**Comment by ninja33** [comment]
emm, I made a new exntension based on your framework to extend the usage of online dictionary.

https://github.com/ninja33/anki-online-dict-helper
